"""add_service_id_to_booking

Revision ID: 2c36333ff91b
Revises: 4dfc1b688311
Create Date: 2024-11-06 23:55:08.711617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c36333ff91b'
down_revision = '4dfc1b688311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_booking_service', 'service', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_service', type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
