"""Add service_id to Booking model

Revision ID: 44809537d38c
Revises: 54c185d1b339
Create Date: 2024-11-01 16:17:36.237341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44809537d38c'
down_revision = '54c185d1b339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_booking_service', 'service', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_service', type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
