"""add date column to timeslot

Revision ID: a602432c38d9
Revises: e8d3bcd40f89
Create Date: 2024-11-13 21:55:52.168620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a602432c38d9'
down_revision = 'e8d3bcd40f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
