"""add user profile fields

Revision ID: af2e7d917c10
Revises: ac68b7e1eece
Create Date: 2024-11-08 21:38:28.438051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2e7d917c10'
down_revision = 'ac68b7e1eece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_bookings', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('completed_bookings')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
